language: php
php:
  - 5.6
  - 7.2
  - hhvm
install:
  - composer self-update
  - composer install --prefer-dist --dev
  - composer info --installed
before_script:
  - mysql -e 'create database amqp_helper_test;'
script: phpunit -c phpunit.xml