language: php
php:
  - 5.6
  - 5.5
  - 5.4
install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install --prefer-dist --dev
  - composer info --installed
before_script:
  - mysql -e 'create database amqp_helper_test;'
script: phpunit --configuration phpunit.xml --coverage-text